spring:
  application:
    name: tdt
  output:
    ansi:
      enabled: always #터미널 output 컬러 설정
  profiles:
    active: local #spring 프로필 설정
  jpa:
    properties:
      hibernate:
        ddl-auto: create #개발용으로 사용
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

server:
  servlet:
    session:
      tracking-modes: cookie #JSESSIONID의 URL 전달 방식 끄기
      timeout: 1800 #1800초(30분)
  error:
    whitelabel:
      enabled: false

#JPA log
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        jdbc:
          bind: TRACE